/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as StockMovementsRouteImport } from './routes/stock-movements'
import { Route as StockRouteImport } from './routes/stock'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as LocationsIdRouteImport } from './routes/locations.$id'
import { Route as AuthedUsersRouteImport } from './routes/_authed/users'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedRolesRouteImport } from './routes/_authed/roles'
import { Route as AuthedAuditLogsRouteImport } from './routes/_authed/audit-logs'

const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const StockMovementsRoute = StockMovementsRouteImport.update({
  id: '/stock-movements',
  path: '/stock-movements',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProductsRoute,
} as any)
const LocationsIdRoute = LocationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LocationsRoute,
} as any)
const AuthedUsersRoute = AuthedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRolesRoute = AuthedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuditLogsRoute = AuthedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/inventory': typeof InventoryRoute
  '/locations': typeof LocationsRouteWithChildren
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRouteWithChildren
  '/signup': typeof SignupRoute
  '/stock': typeof StockRoute
  '/stock-movements': typeof StockMovementsRoute
  '/suppliers': typeof SuppliersRoute
  '/audit-logs': typeof AuthedAuditLogsRoute
  '/roles': typeof AuthedRolesRoute
  '/settings': typeof AuthedSettingsRoute
  '/users': typeof AuthedUsersRoute
  '/locations/$id': typeof LocationsIdRoute
  '/products/$id': typeof ProductsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/inventory': typeof InventoryRoute
  '/locations': typeof LocationsRouteWithChildren
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRouteWithChildren
  '/signup': typeof SignupRoute
  '/stock': typeof StockRoute
  '/stock-movements': typeof StockMovementsRoute
  '/suppliers': typeof SuppliersRoute
  '/audit-logs': typeof AuthedAuditLogsRoute
  '/roles': typeof AuthedRolesRoute
  '/settings': typeof AuthedSettingsRoute
  '/users': typeof AuthedUsersRoute
  '/locations/$id': typeof LocationsIdRoute
  '/products/$id': typeof ProductsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/clients': typeof ClientsRoute
  '/inventory': typeof InventoryRoute
  '/locations': typeof LocationsRouteWithChildren
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRouteWithChildren
  '/signup': typeof SignupRoute
  '/stock': typeof StockRoute
  '/stock-movements': typeof StockMovementsRoute
  '/suppliers': typeof SuppliersRoute
  '/_authed/audit-logs': typeof AuthedAuditLogsRoute
  '/_authed/roles': typeof AuthedRolesRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/users': typeof AuthedUsersRoute
  '/locations/$id': typeof LocationsIdRoute
  '/products/$id': typeof ProductsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients'
    | '/inventory'
    | '/locations'
    | '/login'
    | '/orders'
    | '/products'
    | '/signup'
    | '/stock'
    | '/stock-movements'
    | '/suppliers'
    | '/audit-logs'
    | '/roles'
    | '/settings'
    | '/users'
    | '/locations/$id'
    | '/products/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/inventory'
    | '/locations'
    | '/login'
    | '/orders'
    | '/products'
    | '/signup'
    | '/stock'
    | '/stock-movements'
    | '/suppliers'
    | '/audit-logs'
    | '/roles'
    | '/settings'
    | '/users'
    | '/locations/$id'
    | '/products/$id'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/clients'
    | '/inventory'
    | '/locations'
    | '/login'
    | '/orders'
    | '/products'
    | '/signup'
    | '/stock'
    | '/stock-movements'
    | '/suppliers'
    | '/_authed/audit-logs'
    | '/_authed/roles'
    | '/_authed/settings'
    | '/_authed/users'
    | '/locations/$id'
    | '/products/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ClientsRoute: typeof ClientsRoute
  InventoryRoute: typeof InventoryRoute
  LocationsRoute: typeof LocationsRouteWithChildren
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  SignupRoute: typeof SignupRoute
  StockRoute: typeof StockRoute
  StockMovementsRoute: typeof StockMovementsRoute
  SuppliersRoute: typeof SuppliersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-movements': {
      id: '/stock-movements'
      path: '/stock-movements'
      fullPath: '/stock-movements'
      preLoaderRoute: typeof StockMovementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/locations/$id': {
      id: '/locations/$id'
      path: '/$id'
      fullPath: '/locations/$id'
      preLoaderRoute: typeof LocationsIdRouteImport
      parentRoute: typeof LocationsRoute
    }
    '/_authed/users': {
      id: '/_authed/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthedUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/roles': {
      id: '/_authed/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthedRolesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/audit-logs': {
      id: '/_authed/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthedAuditLogsRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAuditLogsRoute: typeof AuthedAuditLogsRoute
  AuthedRolesRoute: typeof AuthedRolesRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedUsersRoute: typeof AuthedUsersRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAuditLogsRoute: AuthedAuditLogsRoute,
  AuthedRolesRoute: AuthedRolesRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedUsersRoute: AuthedUsersRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface LocationsRouteChildren {
  LocationsIdRoute: typeof LocationsIdRoute
}

const LocationsRouteChildren: LocationsRouteChildren = {
  LocationsIdRoute: LocationsIdRoute,
}

const LocationsRouteWithChildren = LocationsRoute._addFileChildren(
  LocationsRouteChildren,
)

interface ProductsRouteChildren {
  ProductsIdRoute: typeof ProductsIdRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsIdRoute: ProductsIdRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ClientsRoute: ClientsRoute,
  InventoryRoute: InventoryRoute,
  LocationsRoute: LocationsRouteWithChildren,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  ProductsRoute: ProductsRouteWithChildren,
  SignupRoute: SignupRoute,
  StockRoute: StockRoute,
  StockMovementsRoute: StockMovementsRoute,
  SuppliersRoute: SuppliersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
