/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedUsersRouteImport } from './routes/_authed/users'
import { Route as AuthedSuppliersRouteImport } from './routes/_authed/suppliers'
import { Route as AuthedStockMovementsRouteImport } from './routes/_authed/stock-movements'
import { Route as AuthedStockRouteImport } from './routes/_authed/stock'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedRolesRouteImport } from './routes/_authed/roles'
import { Route as AuthedProductsRouteImport } from './routes/_authed/products'
import { Route as AuthedOrdersRouteImport } from './routes/_authed/orders'
import { Route as AuthedLocationsRouteImport } from './routes/_authed/locations'
import { Route as AuthedInventoryRouteImport } from './routes/_authed/inventory'
import { Route as AuthedClientsRouteImport } from './routes/_authed/clients'
import { Route as AuthedAuditLogsRouteImport } from './routes/_authed/audit-logs'
import { Route as AuthedProductsIdRouteImport } from './routes/_authed/products.$id'
import { Route as AuthedLocationsIdRouteImport } from './routes/_authed/locations.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUsersRoute = AuthedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSuppliersRoute = AuthedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStockMovementsRoute = AuthedStockMovementsRouteImport.update({
  id: '/stock-movements',
  path: '/stock-movements',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStockRoute = AuthedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRolesRoute = AuthedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProductsRoute = AuthedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrdersRoute = AuthedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLocationsRoute = AuthedLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInventoryRoute = AuthedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClientsRoute = AuthedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuditLogsRoute = AuthedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProductsIdRoute = AuthedProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedProductsRoute,
} as any)
const AuthedLocationsIdRoute = AuthedLocationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedLocationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/audit-logs': typeof AuthedAuditLogsRoute
  '/clients': typeof AuthedClientsRoute
  '/inventory': typeof AuthedInventoryRoute
  '/locations': typeof AuthedLocationsRouteWithChildren
  '/orders': typeof AuthedOrdersRoute
  '/products': typeof AuthedProductsRouteWithChildren
  '/roles': typeof AuthedRolesRoute
  '/settings': typeof AuthedSettingsRoute
  '/stock': typeof AuthedStockRoute
  '/stock-movements': typeof AuthedStockMovementsRoute
  '/suppliers': typeof AuthedSuppliersRoute
  '/users': typeof AuthedUsersRoute
  '/locations/$id': typeof AuthedLocationsIdRoute
  '/products/$id': typeof AuthedProductsIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/audit-logs': typeof AuthedAuditLogsRoute
  '/clients': typeof AuthedClientsRoute
  '/inventory': typeof AuthedInventoryRoute
  '/locations': typeof AuthedLocationsRouteWithChildren
  '/orders': typeof AuthedOrdersRoute
  '/products': typeof AuthedProductsRouteWithChildren
  '/roles': typeof AuthedRolesRoute
  '/settings': typeof AuthedSettingsRoute
  '/stock': typeof AuthedStockRoute
  '/stock-movements': typeof AuthedStockMovementsRoute
  '/suppliers': typeof AuthedSuppliersRoute
  '/users': typeof AuthedUsersRoute
  '/': typeof AuthedIndexRoute
  '/locations/$id': typeof AuthedLocationsIdRoute
  '/products/$id': typeof AuthedProductsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/audit-logs': typeof AuthedAuditLogsRoute
  '/_authed/clients': typeof AuthedClientsRoute
  '/_authed/inventory': typeof AuthedInventoryRoute
  '/_authed/locations': typeof AuthedLocationsRouteWithChildren
  '/_authed/orders': typeof AuthedOrdersRoute
  '/_authed/products': typeof AuthedProductsRouteWithChildren
  '/_authed/roles': typeof AuthedRolesRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/stock': typeof AuthedStockRoute
  '/_authed/stock-movements': typeof AuthedStockMovementsRoute
  '/_authed/suppliers': typeof AuthedSuppliersRoute
  '/_authed/users': typeof AuthedUsersRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/locations/$id': typeof AuthedLocationsIdRoute
  '/_authed/products/$id': typeof AuthedProductsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/audit-logs'
    | '/clients'
    | '/inventory'
    | '/locations'
    | '/orders'
    | '/products'
    | '/roles'
    | '/settings'
    | '/stock'
    | '/stock-movements'
    | '/suppliers'
    | '/users'
    | '/locations/$id'
    | '/products/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/audit-logs'
    | '/clients'
    | '/inventory'
    | '/locations'
    | '/orders'
    | '/products'
    | '/roles'
    | '/settings'
    | '/stock'
    | '/stock-movements'
    | '/suppliers'
    | '/users'
    | '/'
    | '/locations/$id'
    | '/products/$id'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/audit-logs'
    | '/_authed/clients'
    | '/_authed/inventory'
    | '/_authed/locations'
    | '/_authed/orders'
    | '/_authed/products'
    | '/_authed/roles'
    | '/_authed/settings'
    | '/_authed/stock'
    | '/_authed/stock-movements'
    | '/_authed/suppliers'
    | '/_authed/users'
    | '/_authed/'
    | '/_authed/locations/$id'
    | '/_authed/products/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/users': {
      id: '/_authed/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthedUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/suppliers': {
      id: '/_authed/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthedSuppliersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/stock-movements': {
      id: '/_authed/stock-movements'
      path: '/stock-movements'
      fullPath: '/stock-movements'
      preLoaderRoute: typeof AuthedStockMovementsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/stock': {
      id: '/_authed/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthedStockRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/roles': {
      id: '/_authed/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthedRolesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products': {
      id: '/_authed/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthedProductsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/orders': {
      id: '/_authed/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthedOrdersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/locations': {
      id: '/_authed/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AuthedLocationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/inventory': {
      id: '/_authed/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthedInventoryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/clients': {
      id: '/_authed/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthedClientsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/audit-logs': {
      id: '/_authed/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthedAuditLogsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products/$id': {
      id: '/_authed/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AuthedProductsIdRouteImport
      parentRoute: typeof AuthedProductsRoute
    }
    '/_authed/locations/$id': {
      id: '/_authed/locations/$id'
      path: '/$id'
      fullPath: '/locations/$id'
      preLoaderRoute: typeof AuthedLocationsIdRouteImport
      parentRoute: typeof AuthedLocationsRoute
    }
  }
}

interface AuthedLocationsRouteChildren {
  AuthedLocationsIdRoute: typeof AuthedLocationsIdRoute
}

const AuthedLocationsRouteChildren: AuthedLocationsRouteChildren = {
  AuthedLocationsIdRoute: AuthedLocationsIdRoute,
}

const AuthedLocationsRouteWithChildren = AuthedLocationsRoute._addFileChildren(
  AuthedLocationsRouteChildren,
)

interface AuthedProductsRouteChildren {
  AuthedProductsIdRoute: typeof AuthedProductsIdRoute
}

const AuthedProductsRouteChildren: AuthedProductsRouteChildren = {
  AuthedProductsIdRoute: AuthedProductsIdRoute,
}

const AuthedProductsRouteWithChildren = AuthedProductsRoute._addFileChildren(
  AuthedProductsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAuditLogsRoute: typeof AuthedAuditLogsRoute
  AuthedClientsRoute: typeof AuthedClientsRoute
  AuthedInventoryRoute: typeof AuthedInventoryRoute
  AuthedLocationsRoute: typeof AuthedLocationsRouteWithChildren
  AuthedOrdersRoute: typeof AuthedOrdersRoute
  AuthedProductsRoute: typeof AuthedProductsRouteWithChildren
  AuthedRolesRoute: typeof AuthedRolesRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedStockRoute: typeof AuthedStockRoute
  AuthedStockMovementsRoute: typeof AuthedStockMovementsRoute
  AuthedSuppliersRoute: typeof AuthedSuppliersRoute
  AuthedUsersRoute: typeof AuthedUsersRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAuditLogsRoute: AuthedAuditLogsRoute,
  AuthedClientsRoute: AuthedClientsRoute,
  AuthedInventoryRoute: AuthedInventoryRoute,
  AuthedLocationsRoute: AuthedLocationsRouteWithChildren,
  AuthedOrdersRoute: AuthedOrdersRoute,
  AuthedProductsRoute: AuthedProductsRouteWithChildren,
  AuthedRolesRoute: AuthedRolesRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedStockRoute: AuthedStockRoute,
  AuthedStockMovementsRoute: AuthedStockMovementsRoute,
  AuthedSuppliersRoute: AuthedSuppliersRoute,
  AuthedUsersRoute: AuthedUsersRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
